# Generated by Django 4.2.3 on 2023-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_title',
            field=models.CharField(max_length=64, verbose_name='Task Title'),
        ),
    ]
